language: node_js
node_js: 
  - 11
before_script:
  - npm install @11ty/eleventy -g
script: eleventy
deploy:
  local-dir: /
  provider: pages
  target_branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master