language: node_js
node_js: 
  - 11
before_script:
  - npm install @11ty/eleventy -g
script: eleventy
deploy:
  local-dir: _site
  # fqdn: fdnd.nl
  provider: pages
  target_branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: source